## Cleaning NoseTouch Data for rendering in d3

In [13]:
import pandas as pd
import re
from datetime import datetime

In [14]:
nosetouch_data = pd.read_csv("nosetouch_data.csv")
nosetouch_data.head()

,Date,Time,Hour of the day:,Part of Body,Side,Number of Times,Type,Location,Note
0,Feb 12,15:14,15,Hand,Right,1,NaN,School,NaN
1,Feb 12,15:32,15,Hand,Left,1,NaN,School,NaN
2,Feb 12,15:33,15,Hand,Right,1,NaN,School,NaN
3,Feb 12,15:45,15,Hand,Right,1,NaN,School,NaN
4,Feb 12,15:55,15,Hand,Right,1,NaN,School,NaN

In [15]:
nosetouch_data.info()
nosetouch_data.describe()

nosetouch_data["Type"].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 475 entries, 0 to 474
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              475 non-null    object
 1   Time              475 non-null    object
 2   Hour of the day:  475 non-null    int64
 3   Part of Body      475 non-null    object
 4   Side              473 non-null    object
 5   Number of Times   475 non-null    int64
 6   Type              305 non-null    object
 7   Location          475 non-null    object
 8   Note              5 non-null      object
dtypes: int64(2), object(7)
memory usage: 33.5+ KB

array([nan, 'Scracth', 'Pinch', 'Flick', 'Brush', 'Touch'], dtype=object)

Done
- remove note column
- add underscores to column names
- convert time and date to datetime format

In [16]:
#remove note column
nosetouch_data = nosetouch_data.drop(columns=["Note"])
#all column headers to lowercase, with underscores instead of spaces, remove colons
nosetouch_data.columns = [re.sub(r'[:\s]+', '_', col.lower()) for col in nosetouch_data.columns]
nosetouch_data.head()

,date,time,hour_of_the_day_,part_of_body,side,number_of_times,type,location
0,Feb 12,15:14,15,Hand,Right,1,NaN,School
1,Feb 12,15:32,15,Hand,Left,1,NaN,School
2,Feb 12,15:33,15,Hand,Right,1,NaN,School
3,Feb 12,15:45,15,Hand,Right,1,NaN,School
4,Feb 12,15:55,15,Hand,Right,1,NaN,School

In [17]:
type(nosetouch_data["date"][0]) #string format, so I need to use datetime to convert it to a date format

#create new datetime column from Date and Time columns
    #format for "Date" us MM DD, format for "Time" is HH:MM, year is 2026
nosetouch_data["datetime"] = nosetouch_data.apply(
    lambda row: datetime.strptime(f"{row['date'].strip()} 2026 {row['time'].strip()}", "%b %d %Y %H:%M"), 
    axis=1
)
nosetouch_data.head()


# change all instances of "Brother's Apartment" and "Uncle's Apartment" to "Home"
# change all instance of "Party" and "Giorgia Lupi event" to "Event"
nosetouch_data["location"] = nosetouch_data["location"].replace({
    "Brother's apartment": "Home",
    "Uncle's Apartment": "Home",
    "Party": "Event",
    "Giorgia Lupi event": "Event"
})
nosetouch_data.head()

# In Type, change all flick to "Scratch" and all "Scracth" to "Scratch"
nosetouch_data["type"] = nosetouch_data["type"].replace({
    "Flick": "Scratch",
    "Scracth": "Scratch"
})
nosetouch_data.head()

,date,time,hour_of_the_day_,part_of_body,side,number_of_times,type,location,datetime
0,Feb 12,15:14,15,Hand,Right,1,NaN,School,2026-02-12 15:14:00
1,Feb 12,15:32,15,Hand,Left,1,NaN,School,2026-02-12 15:32:00
2,Feb 12,15:33,15,Hand,Right,1,NaN,School,2026-02-12 15:33:00
3,Feb 12,15:45,15,Hand,Right,1,NaN,School,2026-02-12 15:45:00
4,Feb 12,15:55,15,Hand,Right,1,NaN,School,2026-02-12 15:55:00

In [18]:
nosetouch_data["type"].unique()

array([nan, 'Scratch', 'Pinch', 'Brush', 'Touch'], dtype=object)

In [19]:
#export prepared data to new csv file
nosetouch_data.to_csv("nosetouch_data_prepared.csv", index=False)